# Generated by Django 4.0.6 on 2022-08-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form1',
            new_name='registration_model',
        ),
    ]
